services:
  db:
    image: postgres:15
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: UNIcolas196_
    ports:
      - "5434:5432"
    volumes:
      - blog_postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  blog_postgres_data:
